# -*- coding: utf-8 -*-
"""Apify_Linktree_Profile_Details_Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIzVun8U25jFVegriRQJzoVBDYLHsE99
"""

!pip install apify-client

"""# facebook profile"""

from apify_client import ApifyClient
import pandas as pd

# Initialize the ApifyClient with your Apify API token
# Replace '<YOUR_API_TOKEN>' with your token.
client = ApifyClient("<YOUR_API_TOKEN>")

# Prepare the Actor input
run_input = {
    "proxy": {
        "useApifyProxy": True,
        "apifyProxyCountry": "US",
    },
    "minDelay": 1,
    "maxDelay": 10,
    "profileUrls": ["https://www.facebook.com/techhouse.games.eletronicos"], # Add the profileUrls field here
}

# Run the Actor and wait for it to finish
run = client.actor("curious_coder/facebook-profile-scraper").call(run_input=run_input)

# Fetch and print Actor results from the run's dataset (if there are any)
print("💾 Check your data here: https://console.apify.com/storage/datasets/" + run["defaultDatasetId"])

# Collect the results into a list
results_list = []
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    results_list.append(item)
    # print(item) # Commenting out the print statement

# Create a pandas DataFrame from the results list
df_facebook = pd.DataFrame(results_list)

# Display the DataFrame
display(df_facebook)

# 📚 Want to learn more 📖? Go to → https://docs.apify.com/api/client/python/docs/quick-start

df_facebook.columns



from apify_client import ApifyClient
import pandas as pd

# Initialize the ApifyClient with your Apify API token
# Replace '<YOUR_API_TOKEN>' with your token.
client = ApifyClient("<YOUR_API_TOKEN>")

# Prepare the Actor input
run_input = { "usernames": ["barbeariatradicional"] }

# Run the Actor and wait for it to finish
run = client.actor("apify/instagram-profile-scraper").call(run_input=run_input)

# Fetch and print Actor results from the run's dataset (if there are any)
print("💾 Check your data here: https://console.apify.com/storage/datasets/" + run["defaultDatasetId"])

# Collect the results into a list
results_list = []
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    results_list.append(item)
    # print(item) # Commenting out the print statement

# Create a pandas DataFrame from the results list
df_instagram = pd.DataFrame(results_list)

# Display the DataFrame
display(df_instagram)

df_instagram.to_csv('instagram-profile-scraper-results.csv', index=False)
# 📚 Want to learn more 📖? Go to → https://docs.apify.com/api/client/python/docs/quick-start

df_instagram.iloc[0]['biography']

df_instagram.columns

from apify_client import ApifyClient

# Initialize the ApifyClient with your Apify API token
# Replace '<YOUR_API_TOKEN>' with your token.
client = ApifyClient("<YOUR_API_TOKEN>")

# Prepare the Actor input
run_input = {
    "urls_or_usernames": [
        "https://linktr.ee/tradicionalbarbeariafloripa",
    ],
    "max_retries_per_url": 2,
    "proxy": { "useApifyProxy": False },
}

# Run the Actor and wait for it to finish
run = client.actor("ecomscrape/linktree-profile-details-scraper").call(run_input=run_input)

# Fetch and print Actor results from the run's dataset (if there are any)
print("💾 Check your data here: https://console.apify.com/storage/datasets/" + run["defaultDatasetId"])

# Collect the results into a list
results_list = []
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    results_list.append(item)

# Now results_list contains all the scraped data

import pandas as pd

# Create a list to store flattened data
flattened_data = []

# Iterate through each profile in the results_list
for profile in results_list:
    base_data = {
        'username': profile.get('username'),
        'profile_picture': profile.get('profile_picture'),
        'title': profile.get('title'),
        'description': profile.get('description'),
        'from_url': profile.get('from_url')
    }

    # If there are no links, add the base data and continue
    if not profile.get('links'):
        flattened_data.append(base_data)
    else:
        # Iterate through each link for the current profile
        for link in profile.get('links', []):
            link_data = {
                'link_text': link.get('text'),
                'link_thumbnail': link.get('thumbnail'),
                'link_url': link.get('url')
            }
            # Combine base data with link data
            combined_data = {**base_data, **link_data}
            flattened_data.append(combined_data)

# Create a pandas DataFrame from the flattened data
df_linktree = pd.DataFrame(flattened_data)

# Display the DataFrame
display(df_linktree)
df_linktree.to_csv('linktree-profile-details-scraper_results.csv', index=False)

df_linktree.columns